name : Say Hello

on:
    push:
        branches: main

jobs:
    hellow_pepe:
        runs-on: ubuntu-18.04
        steps:
            - name: Echo the message
              run: |
                echo "Hola que paaisa!!!"

