name : Say Hello

on:
    push:
        branches: main

jobs:
    hellow_pepe:
        runs-on: ubuntu-latest
        steps:
            - name: Echo the message
              run: |
                echo "Hola que paaisa!!!"
            - name: Dime la fecha
              run: date
            - run: ls -l